geobretagne/mreport#187 - correction docker
spelhate/mreport pull request #188
Opened 2022-10-12 15:00 UTC by abonanni

Correction de la dockerisation pour la prise en compte du port

2022-10-12 15:36 UTC, spelhate requested changes
Merci @abonanni

Pouvez-vous cibler la branche develop plutôt que la branche master pour cette PR ?
Merci.

2022-10-12 15:54 UTC, abonanni commented
Voila qui est fait.

2022-10-12 16:33 UTC, abonanni commented
Après analyse ma MR ne gère pas le fait d'avoir des ports différents pour le serveur nginx lui-même et pour l'accès Web via docker.
Je fais une seconde MR

2022-10-13 06:40 UTC, spelhate approved these changes

2022-10-13 06:40 UTC, merged